app = 'hammy'
primary_region = 'lhr'

[build]
  dockerfile = "Dockerfile"


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
